version: 2.1
orbs:
  node: circleci/node@1.1.6

jobs:
  synth:
    executor:
      name: node/default
    steps:
      - checkout
      - setup_remote_docker
      - run: npm ci
      - run: npx cdk synth

workflows:
  synth:
    jobs:
      - synth
